"""empty message

Revision ID: 383359abd8a0
Revises: 78d57cdc532f
Create Date: 2022-07-27 11:31:46.827865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383359abd8a0'
down_revision = '78d57cdc532f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
